use image::{DynamicImage, GenericImageView, ImageBuffer, Rgba, imageops};

pub enum IdSize {
    OneByOne, // 1x1 inch
    TwoByTwo, // 2x2 inch
    Passport, // 35x45 mm
}

pub enum PaperSize {
    FourR, // 4x6 inches
    FiveR, // 5x7 inches
    A4,
}

pub enum LayoutMode {
    Single(IdSize),
    Mixed, // Combo Package
}

pub struct Processor;

impl Processor {
    // Photo loading is now handled asynchronously by the UI

    pub fn adjust_color(
        photo: &DynamicImage,
        brightness: i32,
        contrast: f32,
        sharpen: f32,
    ) -> DynamicImage {
        let mut adjusted = photo.clone();
        if brightness != 0 {
            adjusted = adjusted.brighten(brightness);
        }
        if contrast != 0.0 {
            adjusted = adjusted.adjust_contrast(contrast);
        }
        if sharpen > 0.0 {
            adjusted = DynamicImage::ImageRgba8(imageops::unsharpen(&adjusted, sharpen, 0));
        }
        adjusted
    }

    pub fn ensure_model_downloaded() -> Result<std::path::PathBuf, String> {
        let mut model_dir = gtk::glib::user_cache_dir();
        model_dir.push("photopaper");
        model_dir.push("models");
        
        if !model_dir.exists() {
            std::fs::create_dir_all(&model_dir).map_err(|e| e.to_string())?;
        }
        
        let model_path = model_dir.join("u2net.onnx");
        if model_path.exists() {
            return Ok(model_path);
        }
        
        // Download model
        let url = "https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx";
        let response = ureq::get(url).call().map_err(|e| e.to_string())?;
        
        if response.status() != 200 {
            return Err(format!("Failed to download model: HTTP {}", response.status()));
        }
        
        let mut file = std::fs::File::create(&model_path).map_err(|e| e.to_string())?;
        let mut reader = response.into_reader();
        std::io::copy(&mut reader, &mut file).map_err(|e| e.to_string())?;
        
        Ok(model_path)
    }

    pub fn remove_background_ai(photo: &DynamicImage) -> Result<DynamicImage, String> {
        let model_path = Self::ensure_model_downloaded()?;
        
        let mut manager = rembg_rs::manager::ModelManager::from_file(model_path.as_path())
            .map_err(|e| format!("Failed to load AI model: {:?}", e))?;
            
        let mut options = rembg_rs::options::RemovalOptions::default();
        // Use a high threshold (e.g. 180) to slightly erode the mask so that
        // our subsequent blur doesn't sample the original background pixels (avoiding halos).
        options.threshold = 180;
        options.binary = false;
            
        let result = rembg_rs::rembg::rembg(&mut manager, photo.clone(), &options)
            .map_err(|e| format!("AI processing failed: {:?}", e))?;
            
        let (image, _mask) = result.into_parts();
        
        let width = image.width();
        let height = image.height();
        
        // Extract the alpha channel generated by the AI
        let mut alpha_mask = image::GrayImage::new(width, height);
        for (x, y, pixel) in image.enumerate_pixels() {
            alpha_mask.put_pixel(x, y, image::Luma([pixel[3]]));
        }
        
        // Apply a gentle gaussian blur to smooth out jagged upscaling artifacts from the 320x320 AI model
        let blurred_alpha = image::imageops::blur(&alpha_mask, 2.0);
        
        let mut final_img = image::RgbaImage::new(width, height);
        
        for (x, y, pixel) in image.enumerate_pixels() {
            let mut p = *pixel;
            // Use the smoothed alpha instead of the raw AI alpha
            let alpha = blurred_alpha.get_pixel(x, y)[0] as f32 / 255.0;
            p[0] = (p[0] as f32 * alpha + 255.0 * (1.0 - alpha)) as u8;
            p[1] = (p[1] as f32 * alpha + 255.0 * (1.0 - alpha)) as u8;
            p[2] = (p[2] as f32 * alpha + 255.0 * (1.0 - alpha)) as u8;
            p[3] = 255;
            final_img.put_pixel(x, y, p);
        }
        
        Ok(DynamicImage::ImageRgba8(final_img))
    }

    pub fn remove_background(photo: &DynamicImage, tolerance: f64) -> DynamicImage {
        let img = photo.to_rgba8();
        let (width, height) = img.dimensions();
        
        let mut visited = vec![false; (width * height) as usize];
        let mut queue = std::collections::VecDeque::new();
        
        // Use top-left corner as the primary background reference color
        let bg_color = *img.get_pixel(0, 0);
        
        // Enqueue all border pixels to start flood fill
        for x in 0..width {
            queue.push_back((x, 0));
            queue.push_back((x, height - 1));
        }
        for y in 0..height {
            queue.push_back((0, y));
            queue.push_back((width - 1, y));
        }
        
        // Map tolerance 0.0-1.0 to 0-255 max RGB distance
        let threshold = (tolerance * 255.0) as i32;
        
        let color_diff = |c1: &image::Rgba<u8>, c2: &image::Rgba<u8>| -> i32 {
            let r = (c1[0] as i32 - c2[0] as i32).abs();
            let g = (c1[1] as i32 - c2[1] as i32).abs();
            let b = (c1[2] as i32 - c2[2] as i32).abs();
            r.max(g).max(b)
        };
        
        while let Some((x, y)) = queue.pop_front() {
            let idx = (y * width + x) as usize;
            if visited[idx] {
                continue;
            }
            
            let pixel = img.get_pixel(x, y);
            if color_diff(pixel, &bg_color) <= threshold {
                visited[idx] = true;
                
                if x > 0 { queue.push_back((x - 1, y)); }
                if x < width - 1 { queue.push_back((x + 1, y)); }
                if y > 0 { queue.push_back((x, y - 1)); }
                if y < height - 1 { queue.push_back((x, y + 1)); }
            }
        }
        
        // Create an alpha mask from the flood-fill
        let mut mask = image::GrayImage::from_fn(width, height, |x, y| {
            if visited[(y * width + x) as usize] {
                image::Luma([0]) // Transparent (background)
            } else {
                image::Luma([255]) // Opaque (foreground)
            }
        });
        
        // Erode the mask by 1 pixel so the blur doesn't sample the original background color (prevents color halos)
        let original_mask = mask.clone();
        for y in 1..(height - 1) {
            for x in 1..(width - 1) {
                if original_mask.get_pixel(x, y)[0] == 255 {
                    if original_mask.get_pixel(x - 1, y)[0] == 0 ||
                       original_mask.get_pixel(x + 1, y)[0] == 0 ||
                       original_mask.get_pixel(x, y - 1)[0] == 0 ||
                       original_mask.get_pixel(x, y + 1)[0] == 0 {
                        mask.put_pixel(x, y, image::Luma([0]));
                    }
                }
            }
        }
        
        // Blur the mask to anti-alias / feather the edges
        let blurred_mask = image::imageops::blur(&mask, 1.5);
        
        // Composite original image over white using the feathered mask
        let mut final_img = image::RgbaImage::new(width, height);
        for (x, y, pixel) in img.enumerate_pixels() {
            let mut p = *pixel;
            let alpha = blurred_mask.get_pixel(x, y)[0] as f32 / 255.0;
            
            p[0] = (p[0] as f32 * alpha + 255.0 * (1.0 - alpha)) as u8;
            p[1] = (p[1] as f32 * alpha + 255.0 * (1.0 - alpha)) as u8;
            p[2] = (p[2] as f32 * alpha + 255.0 * (1.0 - alpha)) as u8;
            p[3] = 255;
            
            final_img.put_pixel(x, y, p);
        }
        
        DynamicImage::ImageRgba8(final_img)
    }

    pub fn crop_to_aspect(img: &mut DynamicImage, size: &IdSize) -> DynamicImage {
        let (width, height) = img.dimensions();
        
        let target_aspect = match size {
            IdSize::OneByOne | IdSize::TwoByTwo => 1.0,
            IdSize::Passport => 35.0 / 45.0,
        };

        let current_aspect = width as f32 / height as f32;
        
        let (new_w, new_h) = if current_aspect > target_aspect {
            ((height as f32 * target_aspect) as u32, height)
        } else {
            (width, (width as f32 / target_aspect) as u32)
        };

        let x = (width - new_w) / 2;
        let y = (height - new_h) / 2;

        img.crop(x, y, new_w, new_h)
    }

    fn add_border(photo: &mut DynamicImage) {
        let (width, height) = photo.dimensions();
        let border_color = Rgba([0, 0, 0, 255]); // Solid black border
        let border_thickness = 1; // 1 pixel thick (thinnest possible line at 300 DPI)
        
        let mut img_buf = photo.to_rgba8();
        for t in 0..border_thickness {
            // Top and Bottom
            for x in 0..width {
                img_buf.put_pixel(x, t, border_color);
                img_buf.put_pixel(x, height - 1 - t, border_color);
            }
            // Left and Right
            for y in 0..height {
                img_buf.put_pixel(t, y, border_color);
                img_buf.put_pixel(width - 1 - t, y, border_color);
            }
        }
        
        *photo = DynamicImage::ImageRgba8(img_buf);
    }

    fn resize_photo(photo: &mut DynamicImage, size: &IdSize, target_dims: (u32, u32)) -> DynamicImage {
        let cropped = Self::crop_to_aspect(photo, size);
        let mut resized = cropped.resize_exact(target_dims.0, target_dims.1, imageops::FilterType::Lanczos3);
        Self::add_border(&mut resized);
        resized
    }

    pub fn generate_layout(
        photo: &DynamicImage,
        paper: &PaperSize,
        layout: &LayoutMode,
    ) -> DynamicImage {
        let dpi = 300;
        
        let (canvas_w, canvas_h) = match paper {
            PaperSize::FourR => (4 * dpi, 6 * dpi), // 1200 x 1800
            PaperSize::FiveR => (5 * dpi, 7 * dpi), // 1500 x 2100
            PaperSize::A4 => (2480, 3508), // standard A4 at 300 DPI
        };

        let mut canvas = ImageBuffer::from_fn(canvas_w, canvas_h, |_, _| {
            Rgba([255, 255, 255, 255])
        });

        let mut cropped_photo = photo.clone();
        
        let size_1x1 = (300, 300);
        let size_2x2 = (600, 600);
        let size_passport = (413, 531); 

        let margin = 60; // 0.2 inch safe margin from edges
        let spacing = 0; // No gap between photos for easy edge-to-edge cutting

        match layout {
            LayoutMode::Single(IdSize::TwoByTwo) => {
                let resized = Self::resize_photo(&mut cropped_photo, &IdSize::TwoByTwo, size_2x2);
                let usable_w = canvas_w.saturating_sub(2 * margin);
                let usable_h = canvas_h.saturating_sub(2 * margin);
                
                let cols = (usable_w + spacing) / (size_2x2.0 + spacing);
                let rows = (usable_h + spacing) / (size_2x2.1 + spacing);
                let cols = std::cmp::max(1, cols);
                let rows = std::cmp::max(1, rows);

                let block_w = cols * size_2x2.0 + (cols - 1) * spacing;
                let block_h = rows * size_2x2.1 + (rows - 1) * spacing;
                let start_x = (canvas_w.saturating_sub(block_w)) / 2;
                let start_y = (canvas_h.saturating_sub(block_h)) / 2;
                
                for row in 0..rows {
                    for col in 0..cols {
                        let x = start_x + col * (size_2x2.0 + spacing);
                        let y = start_y + row * (size_2x2.1 + spacing);
                        imageops::overlay(&mut canvas, &resized, x as i64, y as i64);
                    }
                }
            }
            LayoutMode::Single(IdSize::OneByOne) => {
                let resized = Self::resize_photo(&mut cropped_photo, &IdSize::OneByOne, size_1x1);
                let usable_w = canvas_w.saturating_sub(2 * margin);
                let usable_h = canvas_h.saturating_sub(2 * margin);
                
                let cols = (usable_w + spacing) / (size_1x1.0 + spacing);
                let rows = (usable_h + spacing) / (size_1x1.1 + spacing);
                let cols = std::cmp::max(1, cols);
                let rows = std::cmp::max(1, rows);

                let block_w = cols * size_1x1.0 + (cols - 1) * spacing;
                let block_h = rows * size_1x1.1 + (rows - 1) * spacing;
                let start_x = (canvas_w.saturating_sub(block_w)) / 2;
                let start_y = (canvas_h.saturating_sub(block_h)) / 2;

                for row in 0..rows {
                    for col in 0..cols {
                        let x = start_x + col * (size_1x1.0 + spacing);
                        let y = start_y + row * (size_1x1.1 + spacing);
                        imageops::overlay(&mut canvas, &resized, x as i64, y as i64);
                    }
                }
            }
            LayoutMode::Single(IdSize::Passport) => {
                let resized = Self::resize_photo(&mut cropped_photo, &IdSize::Passport, size_passport);
                let usable_w = canvas_w.saturating_sub(2 * margin);
                let usable_h = canvas_h.saturating_sub(2 * margin);
                
                let cols = (usable_w + spacing) / (size_passport.0 + spacing);
                let rows = (usable_h + spacing) / (size_passport.1 + spacing);
                let cols = std::cmp::max(1, cols);
                let rows = std::cmp::max(1, rows);

                let block_w = cols * size_passport.0 + (cols - 1) * spacing;
                let block_h = rows * size_passport.1 + (rows - 1) * spacing;
                let start_x = (canvas_w.saturating_sub(block_w)) / 2;
                let start_y = (canvas_h.saturating_sub(block_h)) / 2;

                for row in 0..rows {
                    for col in 0..cols {
                        let x = start_x + col * (size_passport.0 + spacing);
                        let y = start_y + row * (size_passport.1 + spacing);
                        imageops::overlay(&mut canvas, &resized, x as i64, y as i64);
                    }
                }
            }
            LayoutMode::Mixed => {
                let mut p1 = photo.clone();
                let mut p2 = photo.clone();
                let resized_2x2 = Self::resize_photo(&mut p1, &IdSize::TwoByTwo, size_2x2);
                let resized_1x1 = Self::resize_photo(&mut p2, &IdSize::OneByOne, size_1x1);
                
                let usable_w = canvas_w.saturating_sub(2 * margin);
                let usable_h = canvas_h.saturating_sub(2 * margin);

                match paper {
                    PaperSize::A4 | PaperSize::FiveR => {
                        // Dynamically pack mixed sizes based on usable space
                        let max_2x2_rows = match paper {
                            PaperSize::A4 => 3,
                            _ => 2, // FiveR safely gets 2 rows
                        };
                        let rows_2x2 = std::cmp::min(max_2x2_rows, (usable_h + spacing) / (size_2x2.1 + spacing));
                        let cols_2x2 = (usable_w + spacing) / (size_2x2.0 + spacing);
                        let cols_2x2 = std::cmp::max(1, cols_2x2);
                        let rows_2x2 = std::cmp::max(1, rows_2x2);

                        let remaining_h = usable_h.saturating_sub(rows_2x2 * size_2x2.1 + rows_2x2 * spacing);
                        
                        let cols_1x1 = (usable_w + spacing) / (size_1x1.0 + spacing);
                        let rows_1x1 = (remaining_h + spacing) / (size_1x1.1 + spacing);

                        let block_w = std::cmp::max(
                            cols_2x2 * size_2x2.0 + (cols_2x2.saturating_sub(1)) * spacing,
                            cols_1x1 * size_1x1.0 + (cols_1x1.saturating_sub(1)) * spacing
                        );
                        let block_h = rows_2x2 * size_2x2.1 + (rows_2x2.saturating_sub(1)) * spacing 
                                    + spacing // Gap between 2x2 and 1x1 blocks
                                    + rows_1x1 * size_1x1.1 + (rows_1x1.saturating_sub(1)) * spacing;

                        let start_x = (canvas_w.saturating_sub(block_w)) / 2;
                        let start_y = (canvas_h.saturating_sub(block_h)) / 2;

                        for row in 0..rows_2x2 {
                            for col in 0..cols_2x2 {
                                let x = start_x + (block_w - (cols_2x2 * size_2x2.0 + (cols_2x2 - 1) * spacing)) / 2 + col * (size_2x2.0 + spacing);
                                let y = start_y + row * (size_2x2.1 + spacing);
                                imageops::overlay(&mut canvas, &resized_2x2, x as i64, y as i64);
                            }
                        }

                        let y_offset_1x1 = start_y + rows_2x2 * (size_2x2.1 + spacing);
                        for row in 0..rows_1x1 {
                            for col in 0..cols_1x1 {
                                let x = start_x + (block_w - (cols_1x1 * size_1x1.0 + (cols_1x1 - 1) * spacing)) / 2 + col * (size_1x1.0 + spacing);
                                let y = y_offset_1x1 + row * (size_1x1.1 + spacing);
                                imageops::overlay(&mut canvas, &resized_1x1, x as i64, y as i64);
                            }
                        }
                    }
                    PaperSize::FourR => {
                        // 4R safe layout (1 col of 2x2s on left, 1x1s filling rest)
                        // This strictly respects the 0.2 inch margin + 0.1 inch gaps.
                        let block_w = size_2x2.0 + size_1x1.0 + spacing;
                        let block_h = 2 * (size_2x2.1 + spacing) + size_1x1.1; // 2 rows of 2x2, 1 row of 1x1 at the bottom
                        let start_x = (canvas_w.saturating_sub(block_w)) / 2; 
                        let start_y = (canvas_h.saturating_sub(block_h)) / 2;
                        
                        // Left block: Two 2x2s (1 col, 2 rows)
                        for row in 0..2 {
                            let y = start_y + row * (size_2x2.1 + spacing);
                            imageops::overlay(&mut canvas, &resized_2x2, start_x as i64, y as i64);
                        }
                        
                        // Right block: Four 1x1s (1 col, 4 rows)
                        let right_x = start_x + size_2x2.0 + spacing; 
                        for row in 0..4 {
                            let y = start_y + row * (size_1x1.1 + spacing);
                            imageops::overlay(&mut canvas, &resized_1x1, right_x as i64, y as i64);
                        }
                        
                        // Bottom block: 1x1s below the 2x2s (3 photos across to fill the width)
                        let bottom_y = start_y + 2 * (size_2x2.1 + spacing); 
                        for col in 0..3 {
                            let x = start_x + col * (size_1x1.0 + spacing);
                            imageops::overlay(&mut canvas, &resized_1x1, x as i64, bottom_y as i64);
                        }
                    }
                }
            }
        }

        DynamicImage::ImageRgba8(canvas)
    }
}
